PROJECT_EMOTIONS = [
    "trust",
    "surprise",
    "disgust",
    "anticipation",
    "love",
    "jealousy",
    "shame",
    "embarrassment",
    "pride",
    "gratitude",
    "hope",
    "amazement",
    "admiration",
    "rage",
    "loathing",
    "acceptance",
    "terror",
    "aggressiveness",
    "distraction",
    "boredom",
    "remorse",
    "disapproval"
]

CUSTOM_TO_THEME = {
    "trust": "Devotion / Faith",
    "surprise": "Confusion / Doubt",
    "disgust": "Disgust / Loathing",
    "anticipation": "Motivation / Hope",
    "love": "Love / Devotion",
    "jealousy": "Jealousy / Comparison",
    "shame": "Shame / Embarrassment",
    "embarrassment": "Shame / Embarrassment",
    "pride": "Pride / Ego",
    "gratitude": "Happiness / Joy",
    "hope": "Motivation / Hope",
    "amazement": "Admiration / Amazement",
    "admiration": "Admiration / Amazement",
    "rage": "Anger / Frustration",
    "loathing": "Disgust / Loathing",
    "acceptance": "Peace / Acceptance",
    "terror": "Anxiety / Fear",
    "aggressiveness": "Anger / Frustration",
    "distraction": "Distraction / Lack of Focus",
    "boredom": "Boredom / No Purpose",
    "remorse": "Guilt / Regret / Self-Blame",
    "disapproval": "Disapproval / Inner Conflict"
}